name: Java CI with Maven
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Unit Test
        run: mvn --batch-mode --update-snapshots test
      - name: IT
        if: github.ref == 'refs/heads/master'
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          COUNTRY_CODE: ${{ secrets.COUNTRY_CODE }}
          SN: ${{ secrets.SN }}
        run: mvn --batch-mode --update-snapshots failsafe:integration-test

